// Generated by CoffeeScript 1.7.1
describe("Architecture", function() {});

describe("Wall", function() {
  return describe("surroundingsToBinary", function() {
    return it("returns a binary digit from a 3x3 array", function() {
      var arr;
      arr = [[0, 0, 0], [0, 0, 0], [0, 1, 0]];
      expect(Architecture.surroundingsToBinary(arr)).toEqual("00000100");
      return expect(parseInt(Architecture.surroundingsToBinary(arr), 2) & 4).toEqual(4);
    });
  });
});

//# sourceMappingURL=ArchitectureSpec.map
