// Generated by CoffeeScript 1.7.1
describe("Board", function() {
  var player;
  player = void 0;
  beforeEach(function() {
    return initGame();
  });
  describe("initialization", function() {
    it("creates a new board at level 1", function() {
      return expect(app.board.level).toEqual(1);
    });
    return it("has no children", function() {
      app.board.addChild(new cjs.Shape());
      app.board = initBoard();
      return expect(app.board.getNumChildren()).toEqual(0);
    });
  });
  return describe("room population", function() {});
});

//# sourceMappingURL=BoardSpec.map
