// Generated by CoffeeScript 1.7.1
describe("Board", function() {
  var player;
  player = void 0;
  beforeEach(function() {
    return initGame();
  });
  return it("initializes with a new board at level 1", function() {
    return expect(app.board.level).toEqual(1);
  });
});

//# sourceMappingURL=BoardSpec.map
