// Generated by CoffeeScript 1.7.1
describe("Board", function() {
  describe("initialization", function() {
    it("creates a new board at level 1", function() {
      return expect(app.board.level).toEqual(1);
    });
    return it("has no children", function() {
      app.board.addChild(new cjs.Shape());
      app.board = initBoard();
      return expect(app.board.getNumChildren()).toEqual(0);
    });
  });
  return describe("build tile array", function() {
    it("creates a 12x12 array", function() {
      expect(app.board.tiles.length).toEqual(12);
      return expect(app.board.tiles[11].length).toEqual(12);
    });
    return it("has a Tile Container in each place", function() {
      return expect(app.board.tiles[0][0]).toEqual(jasmine.any(Tile));
    });
  });
});

//# sourceMappingURL=BoardSpec.map
