// Generated by CoffeeScript 1.7.1
describe("Grid", function() {
  var grid;
  grid = null;
  return describe("populate", function() {
    beforeEach(function() {
      return grid = Grid.populate(3, String);
    });
    it("can create a multidimensional array based on size", function() {
      expect(grid.length).toEqual(3);
      return expect(grid[2].length).toEqual(3);
    });
    it("creates a grid with a length 1 less than size", function() {
      expect(grid[2]).not.toBe(void 0);
      return expect(grid[3]).toBe(void 0);
    });
    return it("populates the array with content", function() {
      return expect(grid[1][1]).toEqual(jasmine.any(String));
    });
  });
});

//# sourceMappingURL=GridSpec.map
