// Generated by CoffeeScript 1.7.1
describe("Room", function() {
  var point, room;
  point = null;
  room = null;
  beforeEach(function() {
    point = new cjs.Point(4, 2);
    return room = new Room(point);
  });
  return it("creates a new point", function() {
    expect(room.coords).toEqual(jasmine.any(cjs.Point));
    return expect(room.coords).not.toBe(point);
  });
});

//# sourceMappingURL=RoomSpec.map
