// Generated by CoffeeScript 1.7.1
var emptyBoard;

beforeEach(function() {
  return initGame();
});

emptyBoard = function() {
  app.board.level = 0;
  spyOn(app.board, 'plotPaths');
  return app.board.spawnLevel();
};

//# sourceMappingURL=SpecHelper.map
