// Generated by CoffeeScript 1.7.1
var initBoard;

initBoard = function() {
  var board;
  board = new cjs.Container();
  board = _.extend(board, {
    level: 0,
    tiles: [],
    rooms: [],
    spawnLevel: function() {
      this.level += 1;
      return this.populateRooms();
    },
    populateRooms: function() {},
    buildTileArray: function() {},
    populateRooms: function() {},
    populateStaticTiles: function() {},
    populateRoomTiles: function() {},
    plotPaths: function() {},
    populateDoors: function() {},
    hideRooms: function() {}
  });
  board.spawnLevel();
  return board;
};

//# sourceMappingURL=board.map
