// Generated by CoffeeScript 1.7.1
var initBoard;

initBoard = function() {
  var board;
  board = new cjs.Container();
  board = _.extend(board, {
    level: 0,
    tiles: [],
    rooms: [],
    spawnLevel: function() {
      this.level += 1;
      this.populateRooms();
      return this.buildTileArray();
    },
    buildTileArray: function() {
      var i, j, tile, _i, _results;
      _results = [];
      for (i = _i = 0; _i < 12; i = ++_i) {
        this.tiles[i] = [];
        _results.push((function() {
          var _j, _results1;
          _results1 = [];
          for (j = _j = 0; _j < 12; j = ++_j) {
            tile = new Tile(new cjs.Point(i, j), this.level);
            _results1.push(this.tiles[i].push(tile));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    },
    populateRooms: function() {},
    populateStaticTiles: function() {},
    populateRoomTiles: function() {},
    plotPaths: function() {},
    populateDoors: function() {},
    hideRooms: function() {}
  });
  board.spawnLevel();
  return board;
};

//# sourceMappingURL=Board.map
