// Generated by CoffeeScript 1.7.1
var Hero;

Hero = function() {
  return _.extend(this, app.assets.hero);
};

Hero.prototype = Object.create(cjs.Sprite.prototype);

//# sourceMappingURL=Characters.map
