// Generated by CoffeeScript 1.7.1
var Grid;

Grid = {
  populate: function(size, content) {
    var grid, i, j, _i, _j;
    grid = [];
    for (i = _i = 0; 0 <= size ? _i < size : _i > size; i = 0 <= size ? ++_i : --_i) {
      grid[i] = [];
      for (j = _j = 0; 0 <= size ? _j < size : _j > size; j = 0 <= size ? ++_j : --_j) {
        grid[i][j] = new content(new cjs.Point(i, j));
      }
    }
    return grid;
  }
};

//# sourceMappingURL=Grid.map
