// Generated by CoffeeScript 1.7.1
var app, cjs, initGame, tick;

cjs = createjs;

app = null;

initGame = function() {
  app = new cjs.Stage("ternion");
  app.dispatcher = dispatcher;
  cjs.EventDispatcher.initialize(app.dispatcher);
  app.assets = loadAssets();
  app.hero = new Hero();
  app.board = initBoard();
  app.dispatcher.init();
  cjs.Ticker.addEventListener("tick", tick);
};

tick = function(event) {
  app.update();
};

//# sourceMappingURL=Main.map
