// Generated by CoffeeScript 1.7.1
var Room;

Room = function(point) {
  this.coords = new cjs.Point(point.x, point.y);
  this.name = "";
  this.connected = false;
  this.seeking = false;
  this.exits = [];
  this.contents = [];
};

//# sourceMappingURL=Room.map
