// Generated by CoffeeScript 1.7.1
var initSplash1, initSplash2;

initSplash1 = function() {
  var bg, splash, txt;
  splash = new cjs.Container();
  bg = new cjs.Shape();
  bg.graphics.f("#00f").r(0, 0, 320, 480);
  txt = new cjs.Text("Fooshun Games\nProudly Presents", "20px Arial", "#fff");
  txt.textAlign = "center";
  txt.textBaseline = "middle";
  txt.x = 160;
  txt.y = 240;
  splash.addChild(bg);
  splash.addChild(txt);
  return splash;
};

initSplash2 = function() {
  var bg, splash, txt;
  splash = new cjs.Container();
  bg = new cjs.Shape();
  bg.graphics.f("#00f").r(0, 0, 320, 480);
  txt = new cjs.Text("Ternion", "20px Arial", "#fff");
  txt.textAlign = "center";
  txt.textBaseline = "middle";
  txt.x = 160;
  txt.y = 240;
  splash.addChild(bg);
  splash.addChild(txt);
  return splash;
};

//# sourceMappingURL=Screens.map
