// Generated by CoffeeScript 1.7.1
var initDispatcher;

initDispatcher = function() {
  var State, dispatcher;
  State = function(navList, eventList, screen) {
    var addScreen, afterState, beforeState, duringState, filterCommands, load, removeScreen, unload;
    this.navList = navList;
    this.eventList = eventList;
    this.screen = screen;
    load = function() {
      this.beforeState();
      return this.duringState();
    };
    beforeState = function() {
      this.addScreen();
      return null;
    };
    addScreen = function() {
      app.addChild(this.screen);
      return null;
    };
    duringState = function() {
      return null;
    };
    filterCommands = function() {
      return null;
    };
    unload = function() {
      this.afterState();
      return null;
    };
    afterState = function() {
      this.removeScreen();
      return null;
    };
    return removeScreen = function() {
      app.removeChild(this.screen);
      return null;
    };
  };
  dispatcher = {
    initScreens: function() {
      return this.screens = {
        board: app.board
      };
    },
    initStates: function() {
      return this.states = {
        board: new State([], [], dispatcher.screens.board)
      };
    },
    init: function() {
      this.initScreens();
      this.initStates();
      this.states.board.load;
      return this;
    }
  };
  return dispatcher.init();
};

//# sourceMappingURL=States.map
