// Generated by CoffeeScript 1.7.1
var spawnTile;

spawnTile = function(point) {
  var tile;
  tile = new cjs.Container();
  return tile = _.extend(tile, {
    point: new Point(point.x, point.y)
  });
};

//# sourceMappingURL=Tile.map
