// Generated by CoffeeScript 1.7.1
var Tile;

Tile = function(point, grid) {
  cjs.Container.call(this);
  this.grid = grid;
  this.coords = new cjs.Point(point.x, point.y);
  this.width = 32;
  this.height = 32;
  this.x = this.coords.x * this.width;
  return this.y = this.coords.y * this.height;
};

Tile.prototype = Object.create(cjs.Container.prototype);

Tile.prototype.constructor = Tile;

//# sourceMappingURL=Tile.map
